import type { Branch, Session, SessionType, Staff, User } from "./types"

const today = new Date()
const formatDate = (date: Date) => date.toISOString().split("T")[0]

export const sampleBranches: Branch[] = [
  {
    id: "branch-1",
    name: "vecura-indranagar",
    city: "Bangalore",
    openingHours: {
      Monday: { isOpen: true, startTime: "09:00", endTime: "17:00" },
      Tuesday: { isOpen: true, startTime: "09:00", endTime: "17:00" },
      Wednesday: { isOpen: true, startTime: "09:00", endTime: "17:00" },
      Thursday: { isOpen: true, startTime: "09:00", endTime: "17:00" },
      Friday: { isOpen: true, startTime: "09:00", endTime: "17:00" },
      Saturday: { isOpen: true, startTime: "10:00", endTime: "15:00" },
      Sunday: { isOpen: false, startTime: "10:00", endTime: "15:00" },
    },
  },
  {
    id: "branch-2",
    name: "vecura-koramangala",
    city: "Bangalore",
    openingHours: {
      Monday: { isOpen: true, startTime: "09:00", endTime: "18:00" },
      Tuesday: { isOpen: true, startTime: "09:00", endTime: "18:00" },
      Wednesday: { isOpen: true, startTime: "09:00", endTime: "18:00" },
      Thursday: { isOpen: true, startTime: "09:00", endTime: "18:00" },
      Friday: { isOpen: true, startTime: "09:00", endTime: "18:00" },
      Saturday: { isOpen: true, startTime: "10:00", endTime: "16:00" },
      Sunday: { isOpen: false, startTime: "10:00", endTime: "15:00" },
    },
  },
  {
    id: "branch-3",
    name: "vecura-whitefield",
    city: "Bangalore",
    openingHours: {
      Monday: { isOpen: true, startTime: "08:00", endTime: "17:00" },
      Tuesday: { isOpen: true, startTime: "08:00", endTime: "17:00" },
      Wednesday: { isOpen: true, startTime: "08:00", endTime: "17:00" },
      Thursday: { isOpen: true, startTime: "08:00", endTime: "17:00" },
      Friday: { isOpen: true, startTime: "08:00", endTime: "17:00" },
      Saturday: { isOpen: true, startTime: "09:00", endTime: "15:00" },
      Sunday: { isOpen: false, startTime: "09:00", endTime: "15:00" },
    },
  },
]

// Keep backward compatibility
export const sampleBranch = sampleBranches[0]

export const sampleUsers: User[] = [
  {
    id: "user-1",
    name: "Super Admin",
    email: "superadmin@vcura.com",
    role: "super_admin",
  },
  {
    id: "user-2",
    name: "Indiranagar Admin",
    email: "admin.indiranagar@vcura.com",
    role: "branch_admin",
    branchId: "branch-1",
  },
  {
    id: "user-3",
    name: "Koramangala Admin",
    email: "admin.koramangala@vcura.com",
    role: "branch_admin",
    branchId: "branch-2",
  },
]

export const sampleStaff: Staff[] = [
  {
    id: "staff-1",
    name: "Coach Riya",
    gender: "F",
    role: "Coach",
    phone: "+91-9876543210",
    sessionTypes: ["Cryotherapy", "Body Massage"],
    branchId: "branch-1",
    availability: {
      [formatDate(today)]: { available: true, startTime: "09:00", endTime: "17:00" },
      [formatDate(new Date(today.getTime() + 86400000))]: { available: true, startTime: "09:00", endTime: "17:00" },
      [formatDate(new Date(today.getTime() + 172800000))]: { available: false },
    },
  },
  {
    id: "staff-2",
    name: "Dr. Anita",
    gender: "F",
    role: "Nutritionist",
    phone: "+91-8765432109",
    sessionTypes: ["Diet Consultation"],
    branchId: "branch-1",
    availability: {
      [formatDate(today)]: { available: true, startTime: "10:00", endTime: "18:00" },
      [formatDate(new Date(today.getTime() + 86400000))]: { available: true, startTime: "10:00", endTime: "18:00" },
    },
  },
  {
    id: "staff-3",
    name: "Coach Amit",
    gender: "M",
    role: "Coach",
    phone: "+91-7654321098",
    sessionTypes: ["Cryotherapy", "Laser"],
    branchId: "branch-1",
    availability: {
      [formatDate(today)]: { available: true, startTime: "09:00", endTime: "17:00" },
    },
  },
  {
    id: "staff-4",
    name: "Dr. Priya",
    gender: "F",
    role: "Nutritionist",
    phone: "+91-9123456789",
    sessionTypes: ["Diet Consultation"],
    branchId: "branch-2",
    availability: {
      [formatDate(today)]: { available: true, startTime: "09:00", endTime: "17:00" },
    },
  },
  {
    id: "staff-5",
    name: "Coach Vikram",
    gender: "M",
    role: "Coach",
    phone: "+91-9234567890",
    sessionTypes: ["Cryotherapy", "Body Massage"],
    branchId: "branch-2",
    availability: {
      [formatDate(today)]: { available: true, startTime: "10:00", endTime: "18:00" },
    },
  },
  {
    id: "staff-6",
    name: "Dr. Meera",
    gender: "F",
    role: "Therapist",
    phone: "+91-9345678901",
    sessionTypes: ["Laser", "Body Massage"],
    branchId: "branch-3",
    availability: {
      [formatDate(today)]: { available: true, startTime: "08:00", endTime: "16:00" },
    },
  },
]

export const sampleSessions: Session[] = [
  {
    id: "session-1",
    patientName: "Priya Sharma",
    patientId: "P001",
    phone: "+91-9123456789",
    therapyType: "Cryotherapy",
    staffId: "staff-1",
    branchId: "branch-1",
    date: formatDate(today),
    startTime: "10:30",
    endTime: "11:00",
    status: "Completed",
    whatsappStatus: "Confirmed",
  },
  {
    id: "session-2",
    patientName: "Raj Patel",
    patientId: "P002",
    phone: "+91-9234567890",
    therapyType: "Body Massage",
    staffId: "staff-1",
    branchId: "branch-1",
    date: formatDate(today),
    startTime: "11:30",
    endTime: "12:00",
    status: "Planned",
    whatsappStatus: "Confirmed",
  },
  {
    id: "session-3",
    patientName: "Sophia Lee",
    patientId: "P003",
    phone: "+91-9345678901",
    therapyType: "Diet Consultation",
    staffId: "staff-2",
    branchId: "branch-1",
    date: formatDate(today),
    startTime: "14:00",
    endTime: "14:30",
    status: "No-show",
    whatsappStatus: "No response",
  },
  {
    id: "session-4",
    patientName: "Vikram Singh",
    patientId: "P004",
    phone: "+91-9456789012",
    therapyType: "Cryotherapy",
    staffId: "staff-1",
    branchId: "branch-1",
    date: formatDate(today),
    startTime: "15:00",
    endTime: "15:30",
    status: "Planned",
    whatsappStatus: "Confirmed",
  },
  {
    id: "session-5",
    patientName: "Nisha Gupta",
    patientId: "P005",
    phone: "+91-9567890123",
    therapyType: "Laser",
    staffId: "staff-3",
    branchId: "branch-1",
    date: formatDate(today),
    startTime: "12:00",
    endTime: "12:30",
    status: "Conflict",
    whatsappStatus: "No response",
  },
  {
    id: "session-6",
    patientName: "Anil Kumar",
    patientId: "P006",
    phone: "+91-9678901234",
    therapyType: "Diet Consultation",
    staffId: "staff-4",
    branchId: "branch-2",
    date: formatDate(today),
    startTime: "11:00",
    endTime: "11:30",
    status: "Planned",
    whatsappStatus: "Confirmed",
  },
  {
    id: "session-7",
    patientName: "Sunita Reddy",
    patientId: "P007",
    phone: "+91-9789012345",
    therapyType: "Cryotherapy",
    staffId: "staff-5",
    branchId: "branch-2",
    date: formatDate(today),
    startTime: "14:00",
    endTime: "14:30",
    status: "Completed",
    whatsappStatus: "Confirmed",
  },
  {
    id: "session-8",
    patientName: "Arjun Menon",
    patientId: "P008",
    phone: "+91-9890123456",
    therapyType: "Laser",
    staffId: "staff-6",
    branchId: "branch-3",
    date: formatDate(today),
    startTime: "10:00",
    endTime: "10:20",
    status: "Planned",
    whatsappStatus: "Confirmed",
  },
]

export const sessionTypes: SessionType[] = [
  { id: "type-1", name: "Cryotherapy", durationMinutes: 30 },
  { id: "type-2", name: "Body Massage", durationMinutes: 45 },
  { id: "type-3", name: "Diet Consultation", durationMinutes: 30 },
  { id: "type-4", name: "Laser", durationMinutes: 20 },
]
